// src/constants/colors.js

const palette = {
  lightText: '#1D2E5C',
  lightSecondaryText: '#8B8D98',
  lightBackground: '#FAFBFC',
  lightIcon: '#BFC0C0',
  lightTint: '#0A1045',

  lightPrimary: '#6366F1',
  lightPrimaryLight: '#8B5CF6',
  lightAccent: '#06D6A0',
  lightWarning: '#F59E0B',
  lightError: '#EF4444',
  lightOnPrimary: '#FFFFFF',
  lightGoogleBlue: '#F7F9FF',
  lightInputBackground: '#FFFFFF',
  lightBorder: '#E5E7EB',
  lightBorderLight: '#F3F4F6',
  lightPlaceholder: '#6B7280',
  lightCardBackground: '#FFFFFF',
  lightShadow: '#000000',

  darkText: '#F9FAFB',
  darkSecondaryText: '#D1D5DB',
  darkBackground: '#111827',
  darkIcon: '#D1D5DB',
  darkTint: '#FFFFFF',

  darkPrimary: '#818CF8',
  darkPrimaryLight: '#A78BFA',
  darkAccent: '#34D399',
  darkWarning: '#FBBF24',
  darkError: '#F87171',
  darkOnPrimary: '#1F2937',
  darkGoogleBlue: '#60A5FA',
  darkInputBackground: '#1F2937',
  darkBorder: '#6B7280',
  darkBorderLight: '#4B5563',
  darkPlaceholder: '#9CA3AF',
  darkCardBackground: '#1F2937',
  darkShadow: '#000000',
};

export const Colors = {
  light: {
    text: palette.lightText,
    secondaryText: palette.lightSecondaryText,
    background: palette.lightBackground,
    tint: palette.lightTint,
    icon: palette.lightIcon,
    tabIconDefault: palette.lightIcon,
    tabIconSelected: palette.lightTint,
    primary: palette.lightPrimary,
    primaryLight: palette.lightPrimaryLight,
    accent: palette.lightAccent,
    warning: palette.lightWarning,
    error: palette.lightError,
    onPrimary: palette.lightOnPrimary,
    googleBlue: palette.lightGoogleBlue,
    inputBackground: palette.lightInputBackground,
    border: palette.lightBorder,
    borderLight: palette.lightBorderLight,
    placeholder: palette.lightPlaceholder,
    cardBackground: palette.lightCardBackground,
    shadow: palette.lightShadow,
  },
  dark: {
    text: palette.darkText,
    secondaryText: palette.darkSecondaryText,
    background: palette.darkBackground,
    tint: palette.darkTint,
    icon: palette.darkIcon,
    tabIconDefault: palette.darkIcon,
    tabIconSelected: palette.darkTint,
    primary: palette.darkPrimary,
    primaryLight: palette.darkPrimaryLight,
    accent: palette.darkAccent,
    warning: palette.darkWarning,
    error: palette.darkError,
    onPrimary: palette.darkOnPrimary,
    googleBlue: palette.darkGoogleBlue,
    inputBackground: palette.darkInputBackground,
    border: palette.darkBorder,
    borderLight: palette.darkBorderLight,
    placeholder: palette.darkPlaceholder,
    cardBackground: palette.darkCardBackground,
    shadow: palette.darkShadow,
  },
};

export default Colors;